config/routes.rb
Rails.application.routes.draw do
  resources :friends
  #get 'home/index'
  get 'home/about'
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        #This will redirect the user to the FRIEND CARD (INDIVIDUAL) format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        
        format.html { redirect_to friends_url, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friends_url, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
    <% if friend.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(friend.errors.count, "error") %>
                prohibited this friend from being saved:</h2>

            <ul>
                <% friend.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


    <div>
        <div class="row mb-3">
            <%= form.label :first_name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :first_name, class:"form-control" %>
            </div>
            <br/>
        </div>

        <div class="row mb-3">
            <%= form.label :last_name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :last_name, class:"form-control" %>
            </div>
            <br/>
        </div>

        <div class="row mb-3">
            <%= form.label :email, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.email_field :email, class:"form-control" %>
            </div>
            <br/>
        </div>

        <div class="row mb-3">
            <%= form.label :phone, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.phone_field :phone, class:"form-control" %>
            </div>
            <br/>
        </div>

        <div class="row mb-3">
            <%= form.label :twitter, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :twitter, class:"form-control" %>
            </div>
            <br/>
        </div>

        <div>
            <%= form.submit class:"btn btn-outline-primary" %>
        </div>


    </div>
<% end %>

app/views/friends/_friend.html.erb
    <div id="<%= dom_id friend %>">
        <th scope="row"><%= friend.id %></th>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        
    </div>

app/views/friends/edit.html.erb
<section>
    <div class="container">
        <div>
            
            <%= link_to "Back to friends", friends_path %>
        </div>
        <div class="spacer-20"></div>

        <h1>Editing friend</h1>

        <br/>

        <%= render "form", friend: @friend %>

        <br/>

        

        
    </div>
</section>

app/views/friends/index.html.erb
<main>
    <div class="container">


        <p style="color: blue"><%= notice %></p>

        <div class="spacer-40"></div>

        <div class="friends-index__h1-wrapper">
            <h2>All contacts.</h2>
            <%= link_to "Add New friend", new_friend_path, class:"btn btn-primary" %>
        </div>

        <div class="spacer-40"></div>
        
        <div class="friends-index__cards-wrapper">
            <% @friends.each do |friend| %>
                <div class="friends-index__cards">
                    <div class="cards border" style="padding:20px;">

                        <div class="caption">
                            <h3 class="text-primary"><%= friend.first_name %></h3>
                            <h5><%= friend.last_name %></h5>
                            <br/>

                            <div class="vertical-12">
                                <div>
                                    <small class="small">
                                        Phone:
                                    </small>
                                    <p>
                                        <%= friend.phone%>
                                    </p>
                                </div>

                                <div>
                                    <small class="small">
                                        Email:
                                    </small>
                                    <p>
                                        <%= friend.email%>
                                    </p>
                                </div>

                                <div>
                                    <small class="small">
                                        Twitter:
                                    </small>
                                    <%= link_to friend.twitter, "https://twitter.com/" + friend.twitter, target:"_blabk", style:"display:block;" %>
                                </div>


                            </div>

                            <br/>
                            <div class="vertical-8">
                                <%= link_to "Edit this friend", edit_friend_path(friend.id), class:"btn btn-outline-primary d-block" %>
                                <p style="text-align: center;">
                                    <small> Last edited: <%= friend.updated_at.strftime("%d/%m/%y") %> </small>
                                </p>
                            </div>

                            
                        </div>
                    </div>
                </div>

            <% end %>
        </div>

        <br/>


    </div>
</main>

app/views/friends/new.html.erb
<section>
    <div class="container">

        <div>
            <%= link_to "Back to friends", friends_path %>
        </div>

        <br/>

        <h1>New friend</h1>
        <br/>

        <%= render "form", friend: @friend %>

        <br/>

        

    </div>

</section>

app/views/friends/show.html.erb
<section>
    <div class="container">
        <p style="color: blue"><%= notice %></p>
        <br/>
        <%= link_to "Back to friends", friends_path, class:"link-secondary" %>
        <br/> <br/>
        <div class="row mb-2">
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">
                            <%= @friend.first_name %>
                        </strong>
                        <h3 class="mb-0">
                            <%= @friend.last_name %>
                            <br/><br/>
                        </h3>
                        <p class="card-text mb-auto">
                            <%= @friend.phone %></p>
                        <a href="#" class="stretched-link">
                            <%= @friend.email %></a>
                        <a href="#" class="stretched-link">
                            <%= @friend.twitter %></a>
                    </div>
                </div>
            </div>

        </div>

        <div class="friends-show__btn-wrapper">

            

            <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-outline-primary" %>
            
            

            <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger" %>
        </div>

       

    </div>
</section>

app/views/home/_footer.html.erb
<footer class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Home</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Features</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Pricing</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">FAQs</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Home</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Features</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Pricing</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">FAQs</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Home</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Features</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">Pricing</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">FAQs</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-5 offset-md-1 mb-3">
                <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                        <label for="newsletter1" class="visually-hidden">Email address</label>
                        <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                        <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
            <p>© 2022 Rocha Development, Inc. All rights reserved.</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3">
                    <a class="link-dark" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#twitter"></use>
                        </svg>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="link-dark" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#instagram"></use>
                        </svg>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="link-dark" href="#">
                        <svg class="bi" width="24" height="24">
                            <use xlink:href="#facebook"></use>
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

app/views/home/_header.html.erb
<header>

    <nav>
        <div class="container">
            <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
                <%= link_to 'Rocha Development', root_path,
                    class:"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none"
                %>

                <ul class="nav nav-pills">
                    
                    
                    <li class="nav-item">
                        <a href="/friends" class="nav-link">Friends</a>
                    </li>

                    <li class="nav-item">
                        <a href="/friends/new" class="nav-link">Add Friend</a>
                    </li>



                    <li class="nav-item">
                        <a href="/home/about" class="nav-link">About</a>
                    </li>
                </ul>
            </header>
        </div>
    </nav>
</header>

app/views/home/about.html.erb


<div class="container">
    <br/>
    <h1>This is a bout page</h1>
    <p> This is a paragraph</p>
    <h3>Try not to get caught</h3>

</div>

app/views/home/index.html.erb
<section>
    <div class="container col-xxl-8 px-4">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-sm-12 col-lg-6 hero__image-wrapper" style="
                                                                            display: flex;
                                                                            justify-content: center;">
                <img src="https://images.unsplash.com/photo-1543807535-eceef0bc6599?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" class="d-block mx-lg-auto img-fluid hero__main-image" alt="Bootstrap Themes" width="100%" height="100vh" loading="lazy"></div>
            <div class="col-lg-6">
                <h1 class="display-5 fw-bold lh-1 mb-3">All your contacts in the same place, anywhere.</h1>
                <p class="lead mb-5">Never lose contact information again by changing your cell phone or phone chip. Unlimited contact slots for free!</p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">

                    <%= link_to 'List of contacts', friends_path, class:"btn btn-primary px-4 me-md-2" %>
                    
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Friends App</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </head>

    <body>
        <%= render 'home/header' %>
        <main>
            <%= yield %>
        </main>

        <%= render 'home/footer' %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </body>
</html>